version: '3.9'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
      - OLLAMA_URL=http://ollama:11434
    ports:
      - "9090:9090"
    depends_on:
      - db
    links:
      - db:db
    restart: always
    networks:
      - app-network

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    restart: always
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: