version: '3'

services:
  model-service:
    container_name: case_13_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    command: ./bin/start-gunicorn.sh
